import productImageOne from "../public/Image5.png";
import productImageTwo from "../public/Image6.png";

let data = [
  {
    id: "01",
    title: "Product One",
    price: "$20",
    image: productImageOne, // ✅ reference the variable, not a string
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },{
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
{
    id: "01",
    title: "Product One",
    price: "$20",
    image: productImageOne, // ✅ reference the variable, not a string
  },
  {
    id: "02",
    title: "Product Two",
    price: "$30",
    image: productImageTwo,
  },
  {
    id: "03",
    title: "Product Three",
    price: "$25",
    image: productImageOne,
  },
  {
    id: "04",
    title: "Product Four",
    price: "$15",
    image: productImageTwo,
  },
  {
    id: "05",
    title: "Product Five",
    price: "$10",
    image: productImageOne,
  },
  {
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
{
    id: "06",
    title: "Product Six",
    price: "$7",
    image: productImageTwo,
  },
  {
    id: "07",
    title: "Product Seven",
    price: "$40",
    image: productImageOne,
  },
];

export default data;
